spring:
  data:
    mongodb:
      authentication-database: morphia
      database: morphia
      username: morphia
      password: morphia
      uri: mongodb://localhost:27017
logging:
  level:
    root: info
    com.jipasoft.morphia: debug